-- profiles.lua
-- Generated by wizard.sh. Anchor comments (-- WIZARD_PROFILE_..._BEGIN/END)
-- are used by `wizard.sh add-location` to surgically update individual
-- profiles. Don't remove the anchors.
--
-- Matching rules:
--   1. A profile matches if every device in its `fingerprint` is currently
--      attached (matched by vendorID + productID).
--   2. Among matching profiles, the one with the most fingerprint entries
--      wins ("most specific"). Alphabetical name breaks ties.
--   3. If nothing matches, the engine falls back to "laptop".

return {

  -- WIZARD_PROFILE_laptop_BEGIN
  ["laptop"] = {
    -- Empty fingerprint = always matches (specificity 0). The fallback.
    fingerprint = {
      -- WIZARD_FINGERPRINT_BEGIN
      -- WIZARD_FINGERPRINT_END
    },
    audioInput  = "MacBook Pro Microphone",
    audioOutput = "MacBook Pro Speakers",
    obsScene    = "Laptop",
  },
  -- WIZARD_PROFILE_laptop_END

  -- WIZARD_PROFILE_home-office_BEGIN
  ["home-office"] = {
    fingerprint = {
      -- WIZARD_FINGERPRINT_BEGIN
      { vendorID = 0x2188, productID = 0x6533, name = "CalDigit Thunderbolt 3 Audio (dock)" },
      { vendorID = 0x043e, productID = 0x9a68, name = "LG UltraFine Display Camera" },
      -- WIZARD_FINGERPRINT_END
    },
    audioInput  = "Yeti Stereo Microphone",
    audioOutput = "CalDigit Thunderbolt 3 Audio",
    obsScene    = "Home Office",
  },
  -- WIZARD_PROFILE_home-office_END
}
