#!/usr/bin/env bash
# wizard/_generate-profiles.sh — write a fresh profiles.lua from scratch.
# Args: location names (e.g., "Laptop" "Home Office" "Work Office")
# Used by install.sh on first run. add-location.sh edits in-place via anchors.

# shellcheck disable=SC1091
set -euo pipefail

LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$LIB_DIR/lib.sh"

[[ $# -ge 1 ]] || fail "Usage: _generate-profiles.sh <location1> [location2 ...]"

cat > "$PROFILES_FILE" <<'HEADER'
-- profiles.lua
-- Generated by wizard.sh. Anchor comments (-- WIZARD_PROFILE_..._BEGIN/END)
-- are used by `wizard.sh add-location` to surgically update individual
-- profiles. Don't remove the anchors.
--
-- Matching rules:
--   1. A profile matches if every device in its `fingerprint` is currently
--      attached (matched by vendorID + productID).
--   2. Among matching profiles, the one with the most fingerprint entries
--      wins ("most specific"). Alphabetical name breaks ties.
--   3. If nothing matches, the engine falls back to "laptop".

return {
HEADER

for loc in "$@"; do
  slug=$(to_slug "$loc")
  pretty=$(to_pretty "$slug")
  if [[ "$slug" == "laptop" ]]; then
    cat >> "$PROFILES_FILE" <<LAPTOP_BLOCK

  -- WIZARD_PROFILE_laptop_BEGIN
  ["laptop"] = {
    -- Empty fingerprint = always matches (specificity 0). The fallback.
    fingerprint = {
      -- WIZARD_FINGERPRINT_BEGIN
      -- WIZARD_FINGERPRINT_END
    },
    audioInput  = "MacBook Pro Microphone",
    audioOutput = "MacBook Pro Speakers",
    obsScene    = "Laptop",
  },
  -- WIZARD_PROFILE_laptop_END
LAPTOP_BLOCK
  else
    cat >> "$PROFILES_FILE" <<DOCKED_BLOCK

  -- WIZARD_PROFILE_${slug}_BEGIN
  ["${slug}"] = {
    fingerprint = {
      -- WIZARD_FINGERPRINT_BEGIN
      -- Run \`./wizard.sh add-location\` while docked here to fill these in.
      -- WIZARD_FINGERPRINT_END
    },
    audioInput  = "FILL ME IN",
    audioOutput = "FILL ME IN",
    obsScene    = "${pretty}",
  },
  -- WIZARD_PROFILE_${slug}_END
DOCKED_BLOCK
  fi
done

cat >> "$PROFILES_FILE" <<'FOOTER'
}
FOOTER
